### ISSUE TITLE
対角線のとき旧規格の長い車両を自動的に縮める機能がほしい

### ISSUE THREAD

**Issue by tamaina** [wa-st/Shiftobj#1]
無茶なお願いだと承知でissue立てます。
pak64でもそうですが、diagonal_multiplierが変わってから旧来のアドオンでは、車両が斜め(対角線)にきた時どうしても乱れてします。
そこで、ソフトウェア処理で、Shiftobj(または外部ソフト)で直せることができれば、景観的に貢献することに繋がると思います。
ご検討宜しくお願い致します。

**Comment by wa-st** [comment]
こんばんは。

横向き(SouthWest/NorthEast)の画像を横70％に縮小するだけの簡単な
実装でよければ何とかなりそうな気がします。

ですが、今はpak.nippon-x2をゲームとして機能する状態にして、テスト版
をリリースすることが最優先事項なので、diagonal_multiplier対策は
その後の課題とさせてください。

どうぞよろしくお願いします。

**Comment by tamaina** [comment]
お疲れ様です。
x2楽しみにしております。
